# Generated by Django 6.0.4 on 2026-04-24 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'library',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('WEDDING', 'Wedding'), ('ANNIVERSARY', 'Anniversary'), ('GRADUATION', 'Graduation'), ('CELEBRATION', 'Celebration'), ('CUSTOM', 'Custom')], max_length=20)),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ENERGETIC', 'Energetic'), ('CALM', 'Calm'), ('ROMANTIC', 'Romantic'), ('INSPIRATIONAL', 'Inspirational')], max_length=20)),
                ('singer_tone', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NEUTRAL', 'Neutral'), ('CHILD', 'Child')], max_length=20)),
                ('requested_duration', models.CharField(blank=True, default='3:00', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompt',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('google_id', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='app.library')),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='app.prompt')),
            ],
            options={
                'db_table': 'draft',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file_url', models.URLField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('play_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='app.library')),
            ],
            options={
                'db_table': 'song',
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_token', models.CharField(max_length=200, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_count', models.IntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='app.song')),
            ],
            options={
                'db_table': 'share_link',
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='app.prompt')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_job', to='app.song')),
            ],
            options={
                'db_table': 'generation_job',
            },
        ),
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.CharField(default='0:00', max_length=10)),
                ('is_playing', models.BooleanField(default=False)),
                ('volume', models.FloatField(default=1.0)),
                ('loop_start_time', models.CharField(blank=True, max_length=10)),
                ('loop_end_time', models.CharField(blank=True, max_length=10)),
                ('is_looping', models.BooleanField(default=False)),
                ('current_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_sessions', to='app.song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playback_session', to='app.user')),
            ],
            options={
                'db_table': 'playback_session',
            },
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='app.user'),
        ),
        migrations.CreateModel(
            name='EqualizerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bass_level', models.FloatField(default=0.0)),
                ('mid_level', models.FloatField(default=0.0)),
                ('treble_level', models.FloatField(default=0.0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('playback_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equalizer_presets', to='app.playbacksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalizer_presets', to='app.user')),
            ],
            options={
                'db_table': 'equalizer_preset',
            },
        ),
    ]
