# Generated by Django 6.0.3 on 2026-03-24 04:26

import django.core.validators
import django.db.models.deletion
import domain.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requested_duration', models.CharField(max_length=5, validators=[domain.models.validate_duration])),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('WEDDING', 'Wedding'), ('ANNIVERSARY', 'Anniversary'), ('GRADUATION', 'Graduation'), ('CELEBRATION', 'Celebration'), ('CUSTOM', 'Custom')], max_length=20)),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ENERGETIC', 'Energetic'), ('CALM', 'Calm'), ('ROMANTIC', 'Romantic'), ('INSPIRATIONAL', 'Inspirational')], max_length=20)),
                ('singer_tone', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NEUTRAL', 'Neutral'), ('CHILD', 'Child')], max_length=20)),
            ],
            options={
                'db_table': 'prompts',
            },
        ),
        migrations.CreateModel(
            name='EqualizerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bass_level', models.FloatField(validators=[django.core.validators.MinValueValidator(-12.0), django.core.validators.MaxValueValidator(12.0)])),
                ('mid_level', models.FloatField(validators=[django.core.validators.MinValueValidator(-12.0), django.core.validators.MaxValueValidator(12.0)])),
                ('treble_level', models.FloatField(validators=[django.core.validators.MinValueValidator(-12.0), django.core.validators.MaxValueValidator(12.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equalizer_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equalizer_presets',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Libraries',
                'db_table': 'libraries',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='domain.prompt')),
            ],
            options={
                'db_table': 'drafts',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file_url', models.URLField()),
                ('duration', models.CharField(max_length=5, validators=[domain.models.validate_duration])),
                ('is_favorite', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='domain.library')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='domain.prompt')),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='domain.song')),
            ],
            options={
                'db_table': 'share_links',
            },
        ),
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.CharField(max_length=5)),
                ('is_playing', models.BooleanField(default=False)),
                ('volume', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('loop_start_time', models.CharField(blank=True, max_length=5, null=True)),
                ('loop_end_time', models.CharField(blank=True, max_length=5, null=True)),
                ('is_looping', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playback_session', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to='domain.song')),
            ],
            options={
                'db_table': 'playback_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
